---

language: python

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          python: 2.7
          env: TOXENV=py27
        - os: linux
          dist: xenial
          sudo: required
          python: 2.7
          env: TOXENV=py27

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl

install:
  - pip install ansible
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - ansible-playbook --syntax-check tests/role.yml
  - >
    ansible-playbook --sudo tests/role.yml
    | grep -q '.*failed=1'
    && (echo 'Role test: pass' && exit 0)
    || (echo 'Role test: fail' && exit 1)


webhooks: https://galaxy.ansible.com/api/v1/notifications/

